# Generated by Django 5.0.2 on 2024-02-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability',
            field=models.TextField(blank=True, help_text='Enter your availability for the position.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Enter your motivation for choosing this company.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other',
            field=models.TextField(blank=True, help_text='Enter your answer for any question', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(blank=True, help_text='Write down your skills.', null=True),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.universitycoordinator')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.universitysupervisor')),
            ],
        ),
    ]
