# Generated by Django 5.0.2 on 2024-03-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_evaluation_status_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'submitted'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
