# Generated by Django 5.0.2 on 2024-03-27 14:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_evaluation_status_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='resource_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='resource_video',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Completed', 'Completed')], default='Inprogress', max_length=20),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submitted_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Submitted', 'Submitted'), ('Completed', 'Completed')], default='Inprogress', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('video_instruction', 'Video Instruction'), ('background_info', 'Background Information'), ('task_brief', 'Task Brief'), ('task_resource', 'Task Resource'), ('submit_task', 'Submit Task'), ('example_solution', 'Example Solution')], max_length=250)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_file', models.BooleanField(default=False, help_text='Do you want applicants to submit this task as a file ? e.g txt, pdf, patch, doc')),
                ('is_url', models.BooleanField(default=False, help_text='Do you want applicants to submit this task as a url for the solution ? e.g github link, google drive link')),
                ('is_text', models.BooleanField(default=False, help_text='Do you want applicants to submit this task by writting their answer ?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='posts.task')),
            ],
        ),
    ]
