# Generated by Django 5.0.2 on 2024-04-01 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_certificate_default_text_certificate_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter a price for the Post.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, 'Invalid price for the post')]),
        ),
    ]
