# Generated by Django 5.0.2 on 2024-04-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_evaluation_task_evaluation_submitted_task'),
        ('posts', '0011_paidapplicant'),
    ]

    operations = [
    ]
