# Generated by Django 5.0.2 on 2024-06-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_tasksection_video_alter_post_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksection',
            name='video',
            field=models.URLField(blank=True, help_text='Add a video that explains the task, prefered if you did it from the organization', null=True),
        ),
    ]
