# Generated by Django 5.0.2 on 2024-06-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_poststatus_taskstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='post',
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.task'),
            preserve_default=False,
        ),
    ]
