# Generated by Django 5.0.2 on 2024-06-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_taskstatus_post_taskstatus_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='status',
        ),
    ]
