# Generated by Django 5.0.2 on 2024-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_tasksubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststatus',
            name='allow_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
