# Generated by Django 5.0.2 on 2024-02-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitysupervisor',
            name='coordinator',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='accounts.universitycoordinator'),
            preserve_default=False,
        ),
    ]
