# Generated by Django 5.0.2 on 2024-05-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_universitysupervisor_university_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
    ]
